export enum OWNER_ACTION {
    ADD_COMPANY_NAME = "ADD_COMPANY_NAME"
}

export enum MERCHANT_ACTIONS {
    SET_FULL_NAME = "SET_FULL_NAME",
    SET_COMPANY_NAME = "SET_COMPANY_NAME",
    SET_LOGO_URL = "SET_LOGO_URL",
    SET_MOBILE_NUMBER = "SET_MOBILE_NUMBER",
    SET_WEBSITE_URL = "SET_WEBSITE_URL",
    SET_ADDRESS = "SET_ADDRESS",
    SET_SIGNATURE_URL = "SET_SIGNATURE_URL",
    SET_FOOTNOTE = "SET_FOOTNOTE"
}
