export enum OWNER_ACTION {
    ADD_COMPANY_NAME = "ADD_COMPANY_NAME"
}

export enum MERCHANT_ACTIONS {
    SET_FULL_NAME = "SET_FULL_NAME",
    SET_COMPANY_NAME = "SET_COMPANY_NAME",
    SET_LOGO_URL = "SET_LOGO_URL",
    SET_MOBILE_NUMBER = "SET_MOBILE_NUMBER",
    SET_WEBSITE_URL = "SET_WEBSITE_URL",
    SET_ADDRESS = "SET_ADDRESS",
    SET_SIGNATURE_URL = "SET_SIGNATURE_URL",
    SET_FOOTNOTE = "SET_FOOTNOTE"
}

export enum CUSTOMER_ACTIONS {
    SET_FULL_NAME = "SET_FULL_NAME",
    SET_ADDRESS = "SET_ADDRESS",
    SET_MOBILE_NO = "SET_MOBILE_NO",
    SET_INVOICE_DATE = "SET_INVOICE_DATE",
    SET_INVOICE_NO = "SET_INVOICE_NO",
    SET_PRODUCT_LIST_ITEMS = "SET_PRODUCT_LIST_ITEMS",
    SET_SUBTOTAL_AMOUNT = "SET_SUBTOTAL_AMOUNT",
    SET_TAX_PERCENTAGE = "SET_TAX_PERCENTAGE",
    SET_TOTAL_AMOUNT = "SET_TOTAL_AMOUNT",
    REMOVE_PRODUCT_FROM_LIST = "REMOVE_PRODUCT_FROM_LIST"
}

export enum SCREEN_TO_SHOW {
    CUSTOMER_MODULE = "customer_module",
    MERCHANT_MODULE = "merchant_module",
    PRODUCT_OPERATION = "product_operation"
}